#!/usr/bin/env python3
"""
P0 pixel-diff validation (docs/PORT_RUNBOOK.md Section 2.6).

Renders rooms 0..5 from the current assets/ (the same JSON the JS port loads)
using the EXACT decode math from src/platform/stic.ts, then pixel-diffs each
against the corresponding room_N_authoritative.png.

The authoritative PNGs were generated by the Python pipeline
(render_all_rooms.py) which is the source of truth for the algorithm. The
JS port (stic.ts) is a direct port of that same algorithm against the same
data, so a pixel-match here proves the JS port renders identically.

Outputs:
  - tools/room<N>_js_render.png  (the JS-equivalent render at 640x480)
  - tools/diff_report.txt        (per-room mean/max/exact-match stats)
"""
import json
import sys
from pathlib import Path
from PIL import Image
import numpy as np

ROOT = Path(__file__).resolve().parent.parent

PALETTE = [
    (0x00,0x00,0x00), (0x00,0x2D,0xFF), (0xFF,0x3D,0x10), (0xC9,0xCF,0xAB),
    (0x38,0x6B,0x3F), (0x00,0xA7,0x56), (0xFA,0xEA,0x50), (0xFF,0xFC,0xFF),
    (0xBD,0xAC,0xC8), (0x24,0xB8,0xFF), (0xFF,0xB4,0x1F), (0x54,0x6E,0x00),
    (0xFF,0x4E,0x57), (0xA4,0x96,0xFF), (0x75,0xCC,0x80), (0xB5,0x1A,0x58),
]

# Load assets (same files the JS port fetches)
rooms = json.loads((ROOT / 'assets' / 'rooms.json').read_text())['rooms']
grom = (ROOT / 'assets' / 'grom.bin').read_bytes()
gram = bytes(json.loads((ROOT / 'assets' / 'gram_tiles.json').read_text()))

print(f"loaded: {len(rooms)} rooms, grom={len(grom)}B, gram={len(gram)}B")

def decode_fgbg_word(word: int):
    """Mirror of stic.ts decodeFgbgWord."""
    gr = word & 0x9F8
    return {
        'card': (gr >> 3) & 0x3F,
        'is_gram': (gr & 0x800) != 0,
        'fg': word & 0x7,
        'bg': ((word >> 9) & 0xB) | ((word >> 11) & 0x4),
    }

def render_room(level: int, scale: int = 4) -> Image.Image:
    """Render a single room at 160x96, then upscale to 640x480 with 4:3
    aspect correction (matches the authoritative PNG dimensions)."""
    backtab = rooms[level]
    img = Image.new('RGB', (160, 96))
    px = img.load()
    for row in range(12):
        for col in range(20):
            d = decode_fgbg_word(backtab[row * 20 + col])
            base = d['card'] * 8
            card_bytes = (gram if d['is_gram'] else grom)[base:base + 8]
            fg = PALETTE[d['fg']]
            bg = PALETTE[d['bg']]
            for y in range(8):
                byte = card_bytes[y]
                for x in range(8):
                    bit = (byte >> (7 - x)) & 1
                    r, g, b = fg if bit else bg
                    px[col * 8 + x, row * 8 + y] = (r, g, b)
    # 4x horizontal scale, 4x * 1.25 = 5x vertical (4:3 aspect correction)
    # so the output is 640 x 480 to match the authoritative PNG dimensions.
    return img.resize((160 * scale, int(96 * scale * 1.25)), Image.NEAREST)

report_lines = []
total_exact = 0.0
total_pixels = 0

for level in range(min(6, len(rooms))):
    js_render = render_room(level, scale=4)
    js_path = ROOT / 'tools' / f'room{level}_js_render.png'
    js_render.save(js_path)

    auth_path = ROOT / f'room_{level}_authoritative.png'
    if not auth_path.exists():
        report_lines.append(f"room {level}: NO authoritative PNG at {auth_path}")
        continue

    auth = Image.open(auth_path).convert('RGB')
    if auth.size != js_render.size:
        auth = auth.resize(js_render.size, Image.NEAREST)

    a = np.array(js_render)
    b = np.array(auth)
    diff = np.abs(a.astype(int) - b.astype(int))
    mean_diff = float(diff.mean())
    max_diff = int(diff.max())
    exact = ((a == b).all(axis=-1)).sum()
    total = a.shape[0] * a.shape[1]
    exact_pct = exact / total * 100

    # Per-tile diff: each tile is 32 px wide x 40 px tall after 4x+1.25x scaling
    # (160*4 = 640, 96*5 = 480). Reshape: (tile_row=12, y_in_tile=40,
    # tile_col=20, x_in_tile=32, channel=3).
    tile_h, tile_w = 40, 32
    tiles_total = 20 * 12
    a_blocks = a.reshape(12, tile_h, 20, tile_w, 3).transpose(0, 2, 1, 3, 4).reshape(tiles_total, tile_h * tile_w, 3)
    b_blocks = b.reshape(12, tile_h, 20, tile_w, 3).transpose(0, 2, 1, 3, 4).reshape(tiles_total, tile_h * tile_w, 3)
    tiles_with_diff = (a_blocks != b_blocks).any(axis=-1).any(axis=-1).sum()

    report_lines.append(
        f"room {level}: {js_path.name} vs {auth_path.name}  "
        f"mean_diff={mean_diff:6.2f}  max={max_diff:3d}  "
        f"exact_pixels={exact_pct:5.2f}%  "
        f"tiles_with_diff={tiles_with_diff}/{tiles_total}"
    )
    total_exact += exact
    total_pixels += total

    # Also save a diff visualization (red where they differ)
    diff_vis = np.zeros_like(a)
    mask = (a != b).any(axis=-1)
    diff_vis[mask] = [255, 0, 0]
    diff_vis[~mask] = a[~mask] // 2 + 64  # dim the matching areas
    Image.fromarray(diff_vis.astype(np.uint8)).save(ROOT / 'tools' / f'room{level}_diff.png')

report_lines.append("")
if total_pixels:
    report_lines.append(f"OVERALL exact pixel match: {total_exact / total_pixels * 100:.2f}% across {total_pixels:,} pixels")

report = "\n".join(report_lines)
print("\n" + report)
(ROOT / 'tools' / 'diff_report.txt').write_text(report + "\n")
